import { toast } from "react-toastify";
import { GetModulesByIds, Task } from "@/data/tasks";
import { handleDownload } from "./handleDownload";
import { useLocalStorage } from "@/shared/useLocalStorage";

export interface FileStyle {
    head: string;
    description: string;
    list: Task[];
    footer: string;
}

export function Download() {
    const [selected] = useLocalStorage("selectedModules", []);

    const fileToDownload: FileStyle = {
        head: "ft_transcendence",
        description: "Your selected modules and tasks overview.",
        list: GetModulesByIds(selected),
        footer: "Generated by ft_transcendence Module Selector",
    };

    const handleDownloadClick = () => {
        handleDownload(fileToDownload);
        toast.success("PDF downloaded successfully!");
    };

    return (
        <div
            className="p-4 rounded-2xl bg-pink-900/40 backdrop-blur-md shadow-lg border border-pink-500/40 text-center cursor-pointer hover:bg-pink-900/60 transition"
            onClick={handleDownloadClick}
        >
            <span className="text-xl font-semibold text-pink-200">Download PDF</span>
        </div>
    );
}
